### ISSUE TITLE
Badges have offset when wrapped on new line

### ISSUE THREAD

**Issue by cyckl** [designbylunar/cupid#86] opened 2021-08-06 03:30 UTC
When badges are wrapped to be the only item on a new line, they have an deeper offset.

![image](https://user-images.githubusercontent.com/26363850/128451825-5c82ec76-f385-4f5d-8898-cb57ce8b0890.jpeg)

Most likely due to the mandatory spacing from the end of the text it's attached to. Particularly common on mobile.

**Comment by doamatto** [comment] 2021-08-06 04:12
Dupe of #78.

**Closed by doamatto** 2021-08-06 04:12 UTC
